### ISSUE TITLE
`tugboat create` with options is not picking up default ssh key

### ISSUE THREAD

**Issue by tribou** [pearkes/tugboat#234]
`Tugboat 2.2.0`

After new tugboat installation, I encountered this:

```
> tugboat create dev -s 4gb -i docker -r nyc3
Queueing creation of droplet 'dev'.../Users/user/.rvm/gems/ruby-2.2.1/gems/tugboat-2.2.0/lib/tugboat/middleware/create_droplet.rb:50:in `call': undefined method `split' for nil:NilClass (NoMethodError)
```

My `~/.tugboat` file has the following entry (`access_token` redacted):

```
ssh:
  ssh_user: root
  ssh_key_path: "~/.ssh/id_rsa"
  ssh_port: '22'
defaults:
  region: nyc3
  image: dokku
  size: 512mb
  ssh_key: 1690771
  private_networking: 'false'
  backups_enabled: 'false'
  ip6: 'false'
```

However, when I manually specify the key with the `-k #######` param, it works.
