### ISSUE TITLE
Does Tugboat Support Multiple Teams Yet?

### ISSUE THREAD

**Issue by zlanich** [pearkes/tugboat#247]
I'm a member of 2 DO teams and I can only see Droplets for one of my teams.

**Comment by petems** [comment]
@zlanich Is that possible through the API? I thought each key only allows access to one team

**Comment by mikedevita** [comment]
each key is separate for each team, i would think do would need to release the concept of global keys... but idk

**Comment by zlanich** [comment]
I'm not certain off the top of my head if the API has team support with one API key, but even if you need separate API keys, it would be nice to be able to configure multiple keys, one for each team and to either be able to use a flag to specify which team you're administering or for it to do so automatically if possible.


Best Regards,

Zach Lanich
Business Owner, Entrepreneur, Creative
Owner/Lead Developer
weCreate LLC
www.WeCreate.com

**Comment by mikedevita** [comment]
agreed, some support would be nice, each key is individual to each team i just tested it.

**Comment by zlanich** [comment]
I wish I knew a lick of Ruby. I would have looked into it a while ago lol. 


Best Regards,

Zach Lanich
Business Owner, Entrepreneur, Creative
Owner/Lead Developer
weCreate LLC
www.WeCreate.com

**Comment by mikedevita** [comment]
i know enough to get dangerous lol not enough to consider worthy on contributing any good code though.

**Comment by petems** [comment]
@zlanich @mikedevita It's possible to implement this, just not sure of the UX. Any ideas appreciated?

Would something like an environmental flag be good? 

`TUGBOAT_TEAM=developers tugboat create awesome_app_server`

With a config with multiple team entries:

```
---
authentication:
  developers:
    access_token: b4wf7B7xn6r6TW6Cb4wf7B7xn6r6TW6Cb4wf7B7xn6r6TW6C
  admins:
    access_token: 6SfuFs4ysrVtZHFL6SfuFs4ysrVtZHFL6SfuFs4ysrVtZHFL6SfuF
ssh:
  ssh_user: root
  ssh_key_path: "~/.ssh/id_rsa"
  ssh_port: '22'
defaults:
  region: lon1
  image: centos-6-5-x64
  size: 512mb
  ssh_key: ['foo_key']
  private_networking: 'false'
  backups_enabled: 'false'
  ip6: 'false'
```

As a workaround for now, you could have multiple entries in the ~/.tugboat file and change by commenting and uncommenting for now
